export const FETCH_WALL_OF_ROAR = 'FETCH_WALL_OF_ROAR';
export const FETCH_WALL_OF_ROAR_SUCCESS = 'FETCH_WALL_OF_ROAR_SUCCESS';
export const FETCH_WALL_OF_ROAR_FAILURE = 'FETCH_WALL_OF_ROAR_FAILURE';
